import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import mixins from "./mixins";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.js";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@/styles/abc.css";
import "@/styles/ih_kim.css";
import "@/styles/yuri.css";
const app = createApp(App);
app.use(store);
app.use(router);
app.mixin(mixins);
app.mount("#app");
